### ISSUE TITLE
Module not working at all RN 0.41

### ISSUE THREAD

**Issue by ksegla** [changey/react-native-page-previewer#6]
Hi
I'm on RN 0.41
The module is not working at all
I did

import preview from 'react-native-page-previewer';

then somewhere inside a function

preview("http://www.google.com", function(err, data) {
        console.log("GETPREVIEW2") 
        if(!err) {
            console.log(data);
        }
    });

I can't even get "GETPREVIEW2" to display in the logs

**Comment by ksegla** [comment]
Hi again
You really should change your example or fix your code :).
I had to go and take a look at your code (see below) to realise that your function is taking in an object with "url" as a property, not a string as your example (see below) made it look like.

___Code
function getPreview(urlObj, callback) {
  var url = urlObj.url;

__Example
preview("http://www.google.com", function(err, data) {

**Comment by changey** [comment]
Thanks for the feedback! Would you mind submitting a pull request? I'm happy to merge the change

**Comment by ksegla** [comment]
Thanks but I don't think the churn is enough to go for a PR. The best course of action is probably just for you to change the example as follows:
preview({url:"http://www.google.com"}, function(err, data) {
Thanks :)

**Comment by changey** [comment]
Thanks! updated
