### ISSUE TITLE
Image urls ending in .jpg, .png, etc crash on android

### ISSUE THREAD

**Issue by lucidtheory** [changey/react-native-page-previewer#8]
https://github.com/facebook/react-native/issues/10756

This github issue above is what is showing to cause it. Switching from fetch to axios should fix it. Can we make this fix happen?

**Comment by EsdrasEtrenne** [comment]
There are sometimes warnings on unhandled promise rejections though still, like if the website passed in fails to load or is a bad link. I was going to wrap the axios call in a try catch block to fix this too but that might mess up other pieces of the code. Can you confirm that we can put the axios call in a try catch block?
